<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
		<Authors>G. Gordon Nasseri</Authors>
		<Company>Prophet's Way</Company>
		<Product>Logger</Product>
		<RootNamespace>ProphetsWay.Utilities</RootNamespace>
		<AssemblyName>ProphetsWay.Logger</AssemblyName>
		<PackageId>ProphetsWay.Logger</PackageId>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/ProphetManX/ProphetsWay.Logger</RepositoryUrl>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<ApplicationIcon />
		<Win32Resource />
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<SignAssembly>false</SignAssembly>
		<PackageIcon>profile.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	<Description>
A simple and easy to use Logging library that allows for customizable outputs for log entries.

Go to https://github.com/ProphetManX/ProphetsWay.Logger for more information.

Just one of a few Utility projects I've created for myself and wanted to share.  The namespace for the projects are all "ProphetsWay.Utilities" and the class to use is "Logger".

To Use:
add "using ProphetsWay.Utilities;" to your class

and then you can call the Logger directly.
Logger.AddDestination(new ConsoleDestination());
Logger.Debug("Hello World!");
	</Description>

		<!-- Assembly Override Properties -->
		
		<Version />

		<Copyright />
		<PackageProjectUrl>https://github.com/ProphetManX/ProphetsWay.Logger</PackageProjectUrl>
		<PackageTags>logging;logger;diagnostics</PackageTags>
		<PackageReleaseNotes />
		<NeutralLanguage />
		<AssemblyVersion />
		<FileVersion />
		<InformationalVersion />
		
	</PropertyGroup>

	<PropertyGroup Condition="'$(TF_BUILD)' == 'True'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\CHANGELOG.md" Link="CHANGELOG.md" Pack="true" PackagePath="" />
		<None Include="..\README.md" Link="README.md" Pack="true" PackagePath="" />
		<Content Include="..\profile.png" Link="profile.png" Pack="true" PackagePath="" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
	</ItemGroup>

</Project>
